<?php if (!defined('__TYPECHO_ROOT_DIR__')) exit; ?>
<?php
include __TYPECHO_ADMIN_DIR__ . 'common.php';
$plugin_config = Typecho_Widget::widget('Widget_Options')->plugin('Passport');
$menu->title = _t('找回密码');
// It's important $this refers to Passport_Widget instance here.
// If $this is not available or refers to another widget, explicitly get Passport_Widget.
$passportWidget = Typecho_Widget::widget('Passport_Widget');
include __TYPECHO_ADMIN_DIR__ . 'header.php';
?>
    <style>
        /* --- General Body and Page Structure --- */
        body {
            font-family: "Microsoft YaHei", tahoma, arial, 'Hiragino Sans GB', '\5b8b\4f53', sans-serif;
            background-color: #f5f5f5; /* Light grey background for the page */
            color: #333;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
        }

        .container {
            max-width: 500px; /* Limit width for better readability on larger screens */
            margin-left: auto;
            margin-right: auto;
        }

        .typecho-logo {
            margin: 40px 0 30px;
            text-align: center;
        }

        .typecho-logo h1 {
            margin: 0;
            font-size: 28px;
            font-weight: normal;
        }

        .typecho-logo h1 a {
            color: #333; /* Or your site's primary color */
            text-decoration: none;
        }

        .typecho-page-main {
            margin-top: 20px;
        }

        .typecho-content-panel {
            background-color: #fff;
            border: 1px solid #ddd;
            border-radius: 5px;
            box-shadow: 0 1px 3px rgba(0,0,0,0.05);
        }

        .typecho-table-wrap { /* This is the main container for the form within the panel */
            padding: 30px 40px 40px; /* Adjust padding as needed */
        }

        .typecho-page-title h2 {
            margin: 0 0 30px;
            font-weight: 500;
            font-size: 22px;
            text-align: center;
            color: #444;
        }

        /* --- Form Element Styling (Generated by Typecho_Widget_Helper_Form) --- */
        .typecho-table-wrap form ul,
        .typecho-table-wrap form li {
            list-style-type: none !important; /* Crucial: Removes bullet points */
            margin: 0 0 15px 0 !important; /* Reset margins and add bottom margin to li */
            padding: 0 !important; /* Reset paddings */
        }

        .typecho-table-wrap .typecho-label {
            display: block;
            margin-bottom: 8px;
            font-weight: 600;
            color: #555;
        }

        .typecho-table-wrap .text,
        .typecho-table-wrap input[type="text"],
        .typecho-table-wrap input[type="password"],
        .typecho-table-wrap input[type="email"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box; /* Important for 100% width to include padding and border */
            font-size: 14px;
            transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
        }

        .typecho-table-wrap .text:focus,
        .typecho-table-wrap input[type="text"]:focus,
        .typecho-table-wrap input[type="password"]:focus,
        .typecho-table-wrap input[type="email"]:focus {
            border-color: #007bff; /* Highlight color on focus */
            outline: 0;
            box-shadow: 0 0 0 0.2rem rgba(0,123,255,.25);
        }

        .typecho-table-wrap .description {
            font-size: 0.85em;
            color: #777;
            margin-top: 5px;
            display: block;
        }

        /* --- Submit Button --- */
        .typecho-table-wrap .btn.primary {
            width: 100%;
            height: auto;
            padding: 12px 18px;
            font-size: 16px;
            line-height: 1.5;
            background-color: #007bff; /* Example primary color */
            border-color: #007bff;
            color: #fff;
            border-radius: 4px;
            cursor: pointer;
            transition: background-color 0.2s ease-in-out;
        }

        .typecho-table-wrap .btn.primary:hover {
            background-color: #0056b3;
            border-color: #0056b3;
        }

        .typecho-table-wrap .typecho-option-submit {
            margin-top: 25px; /* Space above the submit button */
        }

        /* --- CAPTCHA Container --- */
        .captcha-container {
            margin-top: 20px; /* Space above CAPTCHA */
            margin-bottom: 20px; /* Space below CAPTCHA */
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 78px; /* Standard reCAPTCHA v2 height */
        }
        .captcha-container > div { /* Direct div child for reCAPTCHA/hCaptcha */
            transform-origin: center center;
        }


        /* --- Notices/Error Messages (from Widget_Notice) --- */
        .typecho-table-wrap .message { /* General notices */
            padding: 15px;
            margin-bottom: 20px;
            border: 1px solid transparent;
            border-radius: 4px;
            text-align: left;
        }
        .typecho-table-wrap .message.error {
            color: #721c24;
            background-color: #f8d7da;
            border-color: #f5c6cb;
        }
        .typecho-table-wrap .message.success {
            color: #155724;
            background-color: #d4edda;
            border-color: #c3e6cb;
        }
        .typecho-table-wrap .message.notice,
        .typecho-table-wrap .message.info { /* Typecho uses 'notice' for info often */
            color: #0c5460;
            background-color: #d1ecf1;
            border-color: #bee5eb;
        }


        /* --- Bottom Links --- */
        .more-link {
            text-align: center;
            margin-top: 30px;
            font-size: 0.9em;
        }

        .more-link a {
            color: #007bff;
            text-decoration: none;
        }

        .more-link a:hover {
            text-decoration: underline;
        }

        /* Responsive adjustments (optional, but good practice) */
        @media (max-width: 600px) {
            .typecho-table-wrap {
                padding: 20px;
            }
            .typecho-logo {
                margin-top: 20px;
                margin-bottom: 20px;
            }
            .typecho-logo h1 {
                font-size: 24px;
            }
            /* Scale down CAPTCHA on small screens if it overflows */
            .captcha-container > div {
                /* Example: scale down. You might need to adjust based on CAPTCHA width */
                /* transform: scale(0.9); */
            }
        }
    </style>
    <div class="body container">
        <div class="typecho-logo"><h1><a href="<?php $passportWidget->options->siteUrl(); ?>"><?php $passportWidget->options->title(); ?></a></h1></div>
        <div class="row typecho-page-main">
            <div class="col-mb-12 col-tb-6 col-tb-offset-3 typecho-content-panel">
                <?php Typecho_Widget::widget('Widget_Notice')->listMessages(); ?>
                <div class="typecho-table-wrap">
                    <div class="typecho-page-title"><h2><?php _e('找回密码'); ?></h2></div>
                    <?php
                    $forgot_form = $passportWidget->forgotForm();
                    ob_start(); $forgot_form->render(); $form_html = ob_get_clean();
                    $csrf_input = '';
                    if (method_exists($passportWidget->security, 'getTokenInput')) { // Ensure security object and method exist
                        $csrf_input = $passportWidget->security->getTokenInput();
                    }

                    $submit_marker = '<button type="submit"'; $pos_submit = strripos($form_html, $submit_marker);
                    if ($pos_submit !== false) {
                        $ul_submit_start_marker = '<ul class="typecho-option typecho-option-submit"';
                        $pos_ul_submit_start = strripos(substr($form_html, 0, $pos_submit), $ul_submit_start_marker);
                        if ($pos_ul_submit_start !== false) $form_html = substr_replace($form_html, $csrf_input, $pos_ul_submit_start, 0);
                        else $form_html = str_replace('</form>', $csrf_input . '</form>', $form_html);
                    } else $form_html = str_replace('</form>', $csrf_input . '</form>', $form_html);

                    // Add hidden field for fallback submission if needed
                    if ($passportWidget->show_fallback_captcha) {
                        $fallback_input = '<input type="hidden" name="is_fallback_submission" value="1" />';
                        // Try to inject it before CSRF or before submit
                        if ($pos_ul_submit_start !== false) $form_html = substr_replace($form_html, $fallback_input, $pos_ul_submit_start, 0);
                        else $form_html = str_replace('</form>', $fallback_input . '</form>', $form_html);
                    }
                    echo $form_html;
                    ?>

                    <?php
                    $display_captcha_provider = '';
                    $captcha_site_key = '';
                    // Determine which CAPTCHA to display (primary non-v3, or fallback)
                    if ($passportWidget->show_fallback_captcha && $plugin_config->captchaProvider == 'recaptcha_v3') {
                        $display_captcha_provider = $plugin_config->v3_fallbackProvider;
                    } elseif (!$passportWidget->show_fallback_captcha && $plugin_config->captchaProvider != 'recaptcha_v3' && $plugin_config->captchaProvider != 'none') {
                        $display_captcha_provider = $plugin_config->captchaProvider;
                    }

                    if ($display_captcha_provider == 'recaptcha_v2') $captcha_site_key = $plugin_config->recaptcha_v2_sitekey;
                    elseif ($display_captcha_provider == 'hcaptcha') $captcha_site_key = $plugin_config->hcaptcha_sitekey;
                    ?>

                    <?php if (!empty($display_captcha_provider) && !empty($captcha_site_key)): ?>
                        <div class="captcha-container">
                            <?php if ($display_captcha_provider == 'recaptcha_v2'): ?>
                                <div class="g-recaptcha" data-sitekey="<?php echo htmlspecialchars($captcha_site_key); ?>"></div>
                            <?php elseif ($display_captcha_provider == 'hcaptcha'): ?>
                                <div class="h-captcha" data-sitekey="<?php echo htmlspecialchars($captcha_site_key); ?>"></div>
                            <?php endif; ?>
                        </div>
                    <?php endif; ?>

                    <?php if (!$passportWidget->show_fallback_captcha && $plugin_config->captchaProvider == 'recaptcha_v3' && !empty($plugin_config->recaptcha_v3_sitekey)): ?>
                        <input type="hidden" name="recaptcha_v3_token" id="recaptcha_v3_token_forgot">
                    <?php endif; ?>

                    <p class="more-link" style="text-align:center; margin-top: 20px;">
                        <a href="<?php $passportWidget->options->siteUrl(); ?>"><?php _e('返回首页'); ?></a> •
                        <a href="<?php $passportWidget->options->adminUrl('login.php'); ?>"><?php _e('用户登录'); ?></a>
                    </p>
                </div>
            </div>
        </div>
    </div>
<?php
include __TYPECHO_ADMIN_DIR__ . 'common-js.php';
if ($display_captcha_provider == 'recaptcha_v2') echo '<script src="https://www.recaptcha.net/recaptcha/api.js" async defer></script>';
elseif ($display_captcha_provider == 'hcaptcha') echo '<script src="https://js.hcaptcha.com/1/api.js" async defer></script>';

// reCAPTCHA v3 script - always include if v3 is primary, for the initial (non-fallback) submission
if ($plugin_config->captchaProvider == 'recaptcha_v3' && !empty($plugin_config->recaptcha_v3_sitekey)) {
    echo '<script src="https://www.recaptcha.net/recaptcha/api.js?render=' . htmlspecialchars($plugin_config->recaptcha_v3_sitekey) . '"></script>';
    echo "<script>
    var forgotFormEl = document.querySelector('form[action=\"" . htmlspecialchars($passportWidget->options->forgotUrl, ENT_QUOTES) . "\"]');
    if (forgotFormEl) {
        var v3TokenFieldForgot = document.getElementById('recaptcha_v3_token_forgot');
        // Only attach submit listener if not already in fallback mode
        if (v3TokenFieldForgot) { 
            forgotFormEl.addEventListener('submit', function(event) {
                if (!v3TokenFieldForgot.value) { // Only execute if token not already set
                    event.preventDefault();
                    grecaptcha.ready(function() {
                        grecaptcha.execute('" . htmlspecialchars($plugin_config->recaptcha_v3_sitekey) . "', {action: 'forgot_password'}).then(function(token) {
                            v3TokenFieldForgot.value = token;
                            forgotFormEl.submit();
                        });
                    });
                }
            });
        }
    }
    </script>";
}
include __TYPECHO_ADMIN_DIR__ . 'footer.php';
?>